# Generated by Django 4.2.7 on 2023-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=2083, null=True)),
                ('address', models.CharField(max_length=2083, null=True)),
            ],
        ),
    ]
