# Generated by Django 4.2.7 on 2023-11-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='click_times',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='last_click_date',
            field=models.DateTimeField(null=True),
        ),
    ]
